services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wroclaw_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret_pass
    ports:
      - "5432:5432"

  backend:
    build: ./back
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:secret_pass@db:5432/wroclaw_db
      - DEBUG=1
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: